# MariaDB作为数据库服务需要和其他服务同时安装
# 在内部网络中存在代理和DNS，数据库服务的域名是指定的服务名'mariadb'，而不是'localhost'或其他形式

version: '2'
services:
  mariadb:
    image: mariadb:10.3
    restart: always
    # 开放端口不是必要的，如果只是内部的服务需要用可以不开放
    #ports:
    #- 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=MyRootPassword
    - MYSQL_USER=user
    - MYSQL_PASSWORD=MyUserPassword
    volumes:
    - /data/mariadb/:/var/lib/mysql
