apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  # 使用ClusterIP时仅集群内部可访问，如果需要开放给集群外部则需要改成NodePort或LoadBalancer
  type: ClusterIP
  ports:
  - name: mysql
    port: 3306
  selector:
    app: mariadb
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mariadb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      serviceAccountName: mariadb
      # 这里使用了hostPath，也可以使用PersistentVolume
      volumes:
      - name: datavolume
        hostPath:
          path: /data/xlpsystem/mariadb
      containers:
      - name: mariadb
        image: mariadb:10.3
        ports:
        - containerPort: 3306
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: datavolume
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: 'MyRootPassword'
        - name: MYSQL_USER
          value: 'user'
        - name: MYSQL_PASSWORD
          vlaue: 'MyUserPassword'
