version: '2'
services:
  logstash:
    #image: docker.elastic.co/logstash/logstash-oss:6.5.2
    build:
      context: ./
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - ./depends:/depends:rw
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
