version: '2'
services:
  elasticsearch:
    #image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.2
    build:
      context: ./
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
